const typographyStyles = {
  '.pretandard-title-1': {
    fontFamily: 'Pretendard',
    fontWeight: 'bold',
    fontSize: '60px',
    lineHeight: '80px',
    letterSpacing: '-1px',
  },
  '.pretandard-title-2': {
    fontFamily: 'Pretendard',
    fontWeight: 'bold',
    fontSize: '48px',
    lineHeight: '68px',
    letterSpacing: '-1px',
  },
  '.pretandard-headline-1': {
    fontFamily: 'Pretendard',
    fontWeight: 'bold',
    fontSize: '36px',
    lineHeight: '56px',
    letterSpacing: '-0.8px',
  },
  '.pretandard-headline-2': {
    fontFamily: 'Pretendard',
    fontWeight: 'bold',
    fontSize: '32px',
    lineHeight: '48px',
    letterSpacing: '-0.8px',
  },
  '.pretandard-headline-3': {
    fontFamily: 'Pretendard',
    fontWeight: 'bold',
    fontSize: '24px',
    lineHeight: '36px',
    letterSpacing: '-0.6px',
  },
  '.pretandard-subtitle-1': {
    fontFamily: 'Pretendard',
    fontWeight: '600',
    fontSize: '18px',
    lineHeight: '28px',
    letterSpacing: '-0.4px',
  },
  '.pretandard-subtitle-2': {
    fontFamily: 'Pretendard',
    fontWeight: '600',
    fontSize: '15px',
    lineHeight: '24px',
    letterSpacing: '-0.4px',
  },
  '.pretandard-subtitle-3': {
    fontFamily: 'Pretendard',
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '24px',
    letterSpacing: '-0.4px',
  },
  '.pretandard-subtitle-5': {
    fontFamily: 'Pretendard',
    fontWeight: '600',
    fontSize: '12px',
    lineHeight: '20px',
    letterSpacing: '-0.2px',
  },
  '.pretandard-body-l': {
    fontFamily: 'Pretendard',
    fontWeight: 'normal',
    fontSize: '24px',
    lineHeight: '32px',
    letterSpacing: '-0.6px',
  },
  '.pretandard-body-1': {
    fontFamily: 'Pretendard',
    fontWeight: 'normal',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '-0.2px',
  },
  '.pretandard-body-2': {
    fontFamily: 'Pretendard',
    fontWeight: 'normal',
    fontSize: '15px',
    lineHeight: '24px',
    letterSpacing: '-0.2px',
  },
  '.pretandard-body-3': {
    fontFamily: 'Pretendard',
    fontWeight: 'normal',
    fontSize: '14px',
    lineHeight: '24px',
    letterSpacing: '-0.2px',
  },
  '.pretandard-body-5': {
    fontFamily: 'Pretendard',
    fontWeight: 'normal',
    fontSize: '12px',
    lineHeight: '20px',
    letterSpacing: '-0.2px',
  },
  '.pretandard-caption-1': {
    fontFamily: 'Pretendard',
    fontWeight: 'normal',
    fontSize: '13px',
    lineHeight: '20px',
    letterSpacing: '-0.2px',
  },
  '.galmuri11-headline-1': {
    fontWeight: 'bold',
    fontSize: '36px',
    lineHeight: '56px',
    letterSpacing: '-0.8px',
  },
  '.galmuri11-headline-2': {
    fontWeight: 'bold',
    fontSize: '28px',
    lineHeight: '40px',
    letterSpacing: '-0.8px',
  },
  '.galmuri11-headline-3': {
    fontWeight: 'bold',
    fontSize: '24px',
    lineHeight: '36px',
    letterSpacing: '-0.6px',
  },
  '.galmuri11-subtitle-1': {
    fontWeight: 'bold',
    fontSize: '18px',
    lineHeight: '28px',
    letterSpacing: '-0.4px',
  },
  '.galmuri11-body-l': {
    fontWeight: 'normal',
    fontSize: '24px',
    lineHeight: '32px',
    letterSpacing: '-0.6px',
  },
  '.galmuri11-body-m': {
    fontWeight: 'normal',
    fontSize: '18px',
    lineHeight: '28px',
    letterSpacing: '-0.4px',
  },
  '.galmuri11-body-1': {
    fontWeight: 'normal',
    fontSize: '16px',
    lineHeight: '28px',
    letterSpacing: '-0.2px',
  },
  '.galmuri11-body-2': {
    fontWeight: 'normal',
    fontSize: '15px',
    lineHeight: '24px',
    letterSpacing: '-0.2px',
  },
  '.galmuri11-body-2-bold': {
    fontWeight: 'bold',
    fontSize: '15px',
    lineHeight: '24px',
    letterSpacing: '-0.2px',
  },
  '.galmuri11-body-3': {
    fontWeight: 'normal',
    fontSize: '14px',
    lineHeight: '24px',
    letterSpacing: '-0.2px',
  },
  '.galmuri11-body-5': {
    fontWeight: 'normal',
    fontSize: '12px',
    lineHeight: '20px',
    letterSpacing: '-0.2px',
  },
};

export default typographyStyles;
