import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const galmuri = localFont({
  src: [
    {
      path: '../../public/assets/fonts/Galmuri11.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/Galmuri11-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-galmuri',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={galmuri.variable}>{children}</body>
    </html>
  );
}
