export const playerList = [
  {
    name: '모승',
    position: 'leader',
    job: 'Front-End',
    description:
      '안녕하세요! 개발자가 천직이라고 생각하는 프론트엔드 개발자 모승입니다:)\n개발도 좋아하고 소통도 좋아해서 같이 친하게 지내요! 저는 프론트와 인프라에 관심이 많아요.\n롤 다이아에요.',
    imageUrl: '/assets/image/people/moseung.jpeg',
  },
  {
    name: 'Lian',
    position: 'manager',
    job: 'Front-End',
    description: '안녕하세요. 프론트엔드 개발자 리안입니다!\n같이 재밌게 활동해요!',
    imageUrl: null,
  },
  {
    name: 'Jane',
    position: 'manager',
    job: 'Front-End',
    description:
      '안녕하세요 :) 프론트엔드 개발자 제인입니다!\n스터디 이외에도 게임이나 다양한 활동 함께해요~!',
    imageUrl: '/assets/image/people/jane.webp',
  },
  {
    name: 'Aaron',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '데이빗',
    position: 'user',
    job: 'Developer',
    description: '-',
    imageUrl: null,
  },
  {
    name: '동원',
    position: 'user',
    job: 'Developer',
    description: '-',
    imageUrl: null,
  },
  {
    name: '든든',
    position: 'user',
    job: 'Developer',
    description: '-',
    imageUrl: null,
  },
  {
    name: '레이첼',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '레코',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: '/assets/image/people/reco.webp',
  },
  {
    name: '로이스',
    position: 'user',
    job: 'Developer',
    description: '3년차 백엔드 개발자입니다!',
    imageUrl: null,
  },
  {
    name: '루키',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '리안',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '서쿤',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '성재',
    position: 'user',
    job: 'Developer',
    description: '-',
    imageUrl: null,
  },
  {
    name: '세이지',
    position: 'user',
    job: 'Designer',
    description: '-',
    imageUrl: null,
  },
  {
    name: 'Sue',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '아사',
    position: 'user',
    job: '-',
    description: '-',
    imageUrl: null,
  },
  {
    name: '앨런',
    position: 'user',
    job: 'Back-End',
    description: '3년차 백엔드입니다. 같이 공부하고 재밌게 해요~!',
    imageUrl: '/assets/image/people/allen.webp',
  },
  {
    name: '엘리사',
    position: 'user',
    job: 'Developer',
    description: '-',
    imageUrl: null,
  },
  {
    name: '울루',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '영준',
    position: 'user',
    job: 'Developer',
    description: '-',
    imageUrl: null,
  },
  {
    name: '제니',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '제레미',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '제파',
    position: 'user',
    job: 'Back-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '준',
    position: 'user',
    job: 'Developer',
    description: '-',
    imageUrl: null,
  },
  {
    name: '주현',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '지수',
    position: 'user',
    job: 'Back-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '클로이',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '타몽',
    position: 'user',
    job: 'Front-End',
    description: '-',
    imageUrl: null,
  },
  {
    name: '하르방',
    position: 'user',
    job: 'App',
    description: '-',
    imageUrl: null,
  },
  {
    name: '혜림',
    position: 'user',
    job: 'Front-End',
    description: '프론트엔드 주니어개발자 혜림입니다\n여행하면서 개발하는게 꿈이예요✨',
    imageUrl: '/assets/image/people/herim.webp',
  },
] as const;

export const positionMap = {
  leader: '스터디장',
  manager: '운영진',
};
